# fly.toml app configuration file generated for fe-wellnesspring-dawn-morning-7728 on 2024-10-14T19:30:47+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fe-wellnesspring-dawn-morning-7728'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
